"""add unique constraint on outcomes.business_id

Revision ID: 2583d9590873
Revises: cf221e601a3b
Create Date: 2026-08-31 14:08:55.065532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2583d9590873'
down_revision: Union[str, Sequence[str], None] = 'cf221e601a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Repository fix round 1: list_leads' outerjoin and get_lead_detail's
    # .one_or_none() both assume at most one Outcome per business, but
    # nothing enforced it -- record_outcome's check-then-insert is a race,
    # not a guarantee. No production data exists yet, so no backfill is
    # needed here.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_outcomes_business_id', 'outcomes', ['business_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_outcomes_business_id', 'outcomes', type_='unique')
    # ### end Alembic commands ###
