"""initial schema

Revision ID: cf221e601a3b
Revises: 
Create Date: 2026-08-29 16:16:25.512953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'cf221e601a3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rulesets',
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('vertical', sa.String(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('search_plan', sa.JSON(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=True),  # end-of-run counts, absent until completion
    sa.Column('max_cost_usd', sa.Float(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppressions',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cid', sa.String(), nullable=False),
    sa.Column('place_id', sa.String(), nullable=True),
    sa.Column('fid', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('phone_is_valid', sa.Boolean(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('segment', sa.Enum('EMERGING', 'GROWTH', 'ESTABLISHED', 'ENTERPRISE', name='segment'), nullable=True),
    sa.Column('primary_category', sa.String(), nullable=True),
    sa.Column('types', sa.JSON(), nullable=True),
    sa.Column('opening_hours', sa.JSON(), nullable=True),
    sa.Column('booking_links', sa.JSON(), nullable=True),
    sa.Column('vertical', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DISCOVERED', 'PLACE_FETCHED', 'SITE_SCRAPED', 'SIGNALS_EXTRACTED', 'SCORED', 'FILTERED_OUT', 'FAILED', name='businessstatus'), nullable=False),
    sa.Column('failed_stage', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['first_seen_run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_cid'), 'businesses', ['cid'], unique=True)
    op.create_index(op.f('ix_businesses_status'), 'businesses', ['status'], unique=False)
    op.create_table('search_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_calls_created_at'), 'api_calls', ['created_at'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manual_facts',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('estimated_employees', sa.Integer(), nullable=True),
    sa.Column('technician_count', sa.Integer(), nullable=True),
    sa.Column('has_office_admin', sa.Boolean(), nullable=True),
    sa.Column('owner_growth_focused', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('business_id')
    )
    op.create_table('outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('contacted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_payloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published_at_is_approximate', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_businesses',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('run_id', 'business_id')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('ruleset_version', sa.String(), nullable=False),
    sa.Column('fit_score', sa.Integer(), nullable=False),
    sa.Column('pain_score', sa.Integer(), nullable=False),
    sa.Column('quadrant', sa.String(), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('scored_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'ruleset_version')
    )
    op.create_table('signals',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('has_booking_link', sa.Boolean(), nullable=True),
    sa.Column('booking_vendor', sa.String(), nullable=True),
    sa.Column('is_phone_only', sa.Boolean(), nullable=True),
    sa.Column('is_24_7', sa.Boolean(), nullable=True),
    sa.Column('closes_before_6pm', sa.Boolean(), nullable=True),
    sa.Column('closed_weekends', sa.Boolean(), nullable=True),
    sa.Column('hours_parse_failed', sa.Boolean(), nullable=True),
    sa.Column('segment', sa.String(), nullable=True),
    sa.Column('has_chat_widget', sa.Boolean(), nullable=True),
    sa.Column('chat_vendor', sa.String(), nullable=True),
    sa.Column('has_contact_form', sa.Boolean(), nullable=True),
    sa.Column('software_from_html', sa.String(), nullable=True),
    sa.Column('runs_google_ads', sa.Boolean(), nullable=True),
    sa.Column('has_meta_pixel', sa.Boolean(), nullable=True),
    sa.Column('claims_24_7', sa.Boolean(), nullable=True),
    sa.Column('website_status', sa.String(), nullable=True),
    sa.Column('team_page_headcount', sa.Integer(), nullable=True),
    sa.Column('review_velocity_90d', sa.Float(), nullable=True),
    sa.Column('missed_call_complaints_90d', sa.Integer(), nullable=True),
    sa.Column('complaint_quotes', sa.JSON(), nullable=True),
    sa.Column('estimated_employees', sa.Integer(), nullable=True),
    sa.Column('employee_est_source', sa.String(), nullable=True),
    sa.Column('has_office_admin', sa.Boolean(), nullable=True),
    sa.Column('owner_growth_focused', sa.Boolean(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.Column('extractor_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('business_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signals')
    op.drop_table('scores')
    op.drop_table('run_businesses')
    op.drop_table('reviews')
    op.drop_table('raw_payloads')
    op.drop_table('outcomes')
    op.drop_table('manual_facts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_api_calls_created_at'), table_name='api_calls')
    op.drop_table('api_calls')
    op.drop_table('search_queries')
    op.drop_index(op.f('ix_businesses_status'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_cid'), table_name='businesses')
    op.drop_table('businesses')
    op.drop_table('suppressions')
    op.drop_table('runs')
    op.drop_table('rulesets')
    # ### end Alembic commands ###
    # autogenerate does not emit DROP TYPE for the Postgres enums it creates
    # on table create; without this, a downgrade-then-upgrade round trip
    # fails with "type already exists" on the next upgrade.
    postgresql.ENUM(name='businessstatus').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='segment').drop(op.get_bind(), checkfirst=True)
